# <center>Atividade 10a</center>
### <center>Aluno: José Henrique Azevedo de Brito</center>
#### <center>Respotas</center>

In [1]:
import numpy as np
import scipy.linalg as sla

In [2]:
def eliminacao(A, b) :
    Ab = np.c_[A, b]
    tam = len(A)
    for i in range(tam - 1) :
        for j in range(i + 1, tam) :
            Ab[j] = Ab[j] - (Ab[j, i] / Ab[i, i]) * Ab[i]
    return Ab[:, : -1], Ab[:, -1]

In [3]:
def pivotamento(Ab , posi) :
    maxPosi = np.abs(Ab[posi :, posi]).argmax() + posi
    Ab[[maxPosi, posi]] = Ab[[posi, maxPosi]]
    return Ab

def eliminacao1(A, b) :
    Ab = np.c_[A, b]
    tam = len(A)
    for i in range(tam - 1) :
        Ab = pivotamento(Ab, i)
        for j in range(i + 1, tam) :
            Ab[j] = Ab[j] - (Ab[j, i] / Ab[i, i]) * Ab[i]
    return Ab[:, : -1], Ab[:, -1]

In [4]:
def calLinearTriSup(A, b) :
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1) :
        x[i] = (b[i] - np.sum(A[i, i + 1 :] * x[i + 1 :])) / A[i, i]
    return x

Teste

In [5]:
A = np.array([[2, 3, -1],[4, 4, -3],[2, -3, 1]])
b = np.array([5, 3, -1])
print("Usando funções feitas do 0")
print(eliminacao1(A, b))
newA, newB = eliminacao1(A, b)
print(calLinearTriSup(newA, newB))
print("Usando NumPy")
print(sla.solve(A, b))

Usando funções feitas do 0
(array([[ 4,  4, -3],
       [ 0, -5,  2],
       [ 0,  0,  0]]), array([ 3, -2,  2]))
[nan inf inf]
Usando NumPy
[1. 2. 3.]


<ipython-input-4-7372e6f024a3>:4: RuntimeWarning: divide by zero encountered in long_scalars
  x[-1] = b[-1] / A[-1, -1]
/home/jose/.anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


A

In [6]:
A = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
b = np.array([1, 2, 0])
print("Usando funções feitas do 0")
print(eliminacao1(A, b))
newA, newB = eliminacao1(A, b)
print(calLinearTriSup(newA, newB))
print("Usando NumPy")
print(sla.solve(A, b))

Usando funções feitas do 0
(array([[ 4,  4,  2],
       [ 0, -1, -2],
       [ 0,  0,  0]]), array([ 2, -1,  0]))
[nan nan nan]
Usando NumPy
[ 1. -1.  1.]


<ipython-input-4-7372e6f024a3>:4: RuntimeWarning: invalid value encountered in long_scalars
  x[-1] = b[-1] / A[-1, -1]


Veja só, segundo o warning do método solve do Scipy, vemos que o calculo do x[-1] que é p x3 ocorre um erro pois b[-1] é zero

B

In [7]:
A = np.array([[7, -7, 1], [-3, 3, 2], [7, 7, -72]])
b = np.array([1, 2, 7])
print("Usando funções feitas do 0")
print(eliminacao1(A, b))
newA, newB = eliminacao1(A, b)
print(calLinearTriSup(newA, newB))
print("Usando NumPy")
print(sla.solve(A, b))

Usando funções feitas do 0
(array([[  7,  -7,   1],
       [  0,  14, -73],
       [  0,   0,   2]]), array([1, 6, 2]))
[5.64285714 5.64285714 1.        ]
Usando NumPy
[5.64285714 5.64285714 1.        ]


C

In [9]:
A = np.array([[1, 2, 3, 4], [2, 2, 3, 4], [3, 3, 3, 4], [4, 4, 4, 4]])
b = np.array([20, 22, 22, 24])
print("Usando funções feitas do 0")
print(eliminacao1(A, b))
newA, newB = eliminacao1(A, b)
print(calLinearTriSup(newA, newB))
print("Usando NumPy")
print(sla.solve(A, b))

Usando funções feitas do 0
(array([[4, 4, 4, 4],
       [0, 1, 2, 3],
       [0, 0, 1, 2],
       [0, 0, 0, 1]]), array([24, 14, 10,  4]))
[ 2. -2.  2.  4.]
Usando NumPy
[ 2. -2.  2.  4.]
