# <center>Atividade 10b</center>
### <center>Aluno: José Henrique Azevedo de Brito</center>
#### <center>Respotas</center>

In [49]:
import numpy as np
import scipy.linalg as sla
import copy as cp

In [50]:
def pivotamento(P, U, posi) :
    maxPosi = np.abs(U[posi :, posi]).argmax() + posi
    U[[maxPosi, posi]] = U[[posi, maxPosi]]
    P[[maxPosi, posi]] = P[[posi, maxPosi]]
    return P, U

def eliminacao(P, L, U) :
    tam = len(U)
    for j in range(tam - 1) :
        P, U = pivotamento(P, U, j)
        for i in range(j + 1, tam) :
            L[i, j] = U[i, j] / U[j, j]
            U[i] = U[i] - L[i, j] * U[j]
    return P, L, U

def calLinearTriSup(A, b) :
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1) :
        x[i] = (b[i] - np.sum(A[i, i + 1 :] * x[i + 1 :])) / A[i, i]
    return x

def calLinearTriInf(A, b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[0] / A[0, 0]
    for i in range(1, n):
        x[i] = (b[i] - np.sum(A[i,: i] * x[: i])) / A[i, i]   
    return x

def lu_solve(A, b) :
    P, L, U = eliminacao(np.eye(len(A)), np.eye(len(A)), cp.deepcopy(A))
    y = calLinearTriInf(L, P @ b)
    x = calLinearTriSup(U, y)
    return x


Testes

In [51]:
A = np.array([[1,1,1],[2,1,-1],[2,-1,1]])
b = np.array([-2,1,3])
P, L, U = eliminacao(np.eye(len(A)), np.eye(len(A)), cp.deepcopy(A))
print("P, L, U e x usando funções feitas do 0")
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", lu_solve(A, b), "\n")
print("P, L, U e x usando funções do SciPy.linalg")
P, L, U = sla.lu(A)
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", sla.lu_solve(sla.lu_factor(A), b))

P, L, U e x usando funções feitas do 0
P = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 1.  -0.   1. ]]
U = [[ 2  1 -1]
 [ 0 -2  2]
 [ 0  0  1]]
P@L@U = [[ 1.  -1.5  1.5]
 [ 2.   1.   0. ]
 [ 2.   1.  -1. ]]
x = [ 1.125 -4.25  -3.   ] 

P, L, U e x usando funções do SciPy.linalg
P = [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L = [[ 1.    0.    0.  ]
 [ 1.    1.    0.  ]
 [ 0.5  -0.25  1.  ]]
U = [[ 2.  1. -1.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
P@L@U = [[ 1.  1.  1.]
 [ 2.  1. -1.]
 [ 2. -1.  1.]]
x = [ 1. -2. -1.]


In [52]:
A = np.array([[1,1,0],[2,1,-1],[3,-1,-1]])
b = np.array([-2,1,3])
P, L, U = eliminacao(np.eye(len(A)), np.eye(len(A)), cp.deepcopy(A))
print("P, L, U e x usando funções feitas do 0")
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", lu_solve(A, b), "\n")
print("P, L, U e x usando funções do SciPy.linalg")
P, L, U = sla.lu(A)
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", sla.lu_solve(sla.lu_factor(A), b))

P, L, U e x usando funções feitas do 0
P = [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L = [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 1.         1.        ]]
U = [[ 3 -1 -1]
 [ 0  1  0]
 [ 0  0  0]]
P@L@U = [[ 1.          0.66666667 -0.33333333]
 [ 2.          0.33333333 -0.66666667]
 [ 3.         -1.         -1.        ]]
x = [ nan  nan -inf] 

P, L, U e x usando funções do SciPy.linalg
P = [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L = [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
U = [[ 3.         -1.         -1.        ]
 [ 0.          1.66666667 -0.33333333]
 [ 0.          0.          0.6       ]]
P@L@U = [[ 1.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 2.00000000e+00  1.00000000e+00 -1.00000000e+00]
 [ 3.00000000e+00 -1.00000000e+00 -1.00000000e+00]]
x = [-0.66666667 -1.33333333 -3.66666667]


<ipython-input-50-e2637084ed6c>:19: RuntimeWarning: divide by zero encountered in double_scalars
  x[-1] = b[-1] / A[-1, -1]
<ipython-input-50-e2637084ed6c>:21: RuntimeWarning: invalid value encountered in multiply
  x[i] = (b[i] - np.sum(A[i, i + 1 :] * x[i + 1 :])) / A[i, i]


A

In [53]:
A = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
b = np.array([1, 2, 0])
P, L, U = eliminacao(np.eye(len(A)), np.eye(len(A)), cp.deepcopy(A))
print("P, L, U e x usando funções feitas do 0")
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", lu_solve(A, b), "\n")
print("P, L, U e x usando funções do SciPy.linalg")
P, L, U = sla.lu(A)
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", sla.lu_solve(sla.lu_factor(A), b))

P, L, U e x usando funções feitas do 0
P = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.    1.  ]]
U = [[ 4  4  2]
 [ 0 -1 -2]
 [ 0  0  0]]
P@L@U = [[ 1.   0.  -1.5]
 [ 2.   2.   1. ]
 [ 4.   4.   2. ]]
x = [nan nan nan] 

P, L, U e x usando funções do SciPy.linalg
P = [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L = [[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [ 0.25 -0.    1.  ]]
U = [[ 4.   4.   2. ]
 [ 0.  -1.  -2. ]
 [ 0.   0.   0.5]]
P@L@U = [[ 1.  1.  1.]
 [ 4.  4.  2.]
 [ 2.  1. -1.]]
x = [ 1. -1.  1.]


<ipython-input-50-e2637084ed6c>:19: RuntimeWarning: invalid value encountered in double_scalars
  x[-1] = b[-1] / A[-1, -1]


B

In [54]:
A = np.array([[7, -7, 1], [-3, 3, 2], [7, 7, -72]])
b = np.array([1, 2, 7])
P, L, U = eliminacao(np.eye(len(A)), np.eye(len(A)), cp.deepcopy(A))
print("P, L, U e x usando funções feitas do 0")
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", lu_solve(A, b), "\n")
print("P, L, U e x usando funções do SciPy.linalg")
P, L, U = sla.lu(A)
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", sla.lu_solve(sla.lu_factor(A), b))

P, L, U e x usando funções feitas do 0
P = [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L = [[ 1.          0.          0.        ]
 [-0.42857143  1.          0.        ]
 [ 1.          0.          1.        ]]
U = [[  7  -7   1]
 [  0  14 -73]
 [  0   0   2]]
P@L@U = [[  7.          -7.           1.        ]
 [  7.          -7.           3.        ]
 [ -3.          17.         -73.42857143]]
x = [3.20918367 3.1377551  0.5       ] 

P, L, U e x usando funções do SciPy.linalg
P = [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L = [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-4.28571429e-01  1.18952467e-17  1.00000000e+00]]
U = [[  7.          -7.           1.        ]
 [  0.          14.         -73.        ]
 [  0.           0.           2.42857143]]
P@L@U = [[  7.  -7.   1.]
 [ -3.   3.   2.]
 [  7.   7. -72.]]
x = [5.64285714 5.64285714 1.        ]


C

In [55]:
A = np.array([[1, 2, 3, 4], [2, 2, 3, 4], [3, 3, 3, 4], [4, 4, 4, 4]])
b = np.array([20, 22, 22, 24])
P, L, U = eliminacao(np.eye(len(A)), np.eye(len(A)), cp.deepcopy(A))
print("P, L, U e x usando funções feitas do 0")
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", lu_solve(A, b), "\n")
print("P, L, U e x usando funções do SciPy.linalg")
P, L, U = sla.lu(A)
print("P =", P)
print("L =", L)
print("U =", U)
print("P@L@U =", P@L@U)
print("x =", sla.lu_solve(sla.lu_factor(A), b))

P, L, U e x usando funções feitas do 0
P = [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
L = [[1.   0.   0.   0.  ]
 [0.5  1.   0.   0.  ]
 [0.75 0.   1.   0.  ]
 [0.25 0.   0.   1.  ]]
U = [[4 4 4 4]
 [0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]]
P@L@U = [[1. 1. 1. 2.]
 [4. 4. 4. 4.]
 [2. 3. 4. 5.]
 [3. 3. 4. 5.]]
x = [  2.  16. -28.  16.] 

P, L, U e x usando funções do SciPy.linalg
P = [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
L = [[1.   0.   0.   0.  ]
 [0.25 1.   0.   0.  ]
 [0.5  0.   1.   0.  ]
 [0.75 0.   0.   1.  ]]
U = [[4. 4. 4. 4.]
 [0. 1. 2. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]
P@L@U = [[1. 2. 3. 4.]
 [2. 2. 3. 4.]
 [3. 3. 3. 4.]
 [4. 4. 4. 4.]]
x = [ 2. -2.  2.  4.]


E o método implementado do zero não foi 100% éficaz e preciso comparado ao métodos métodos usados do scipy.linalg! Em alguns momento no pivotamento, a escolha do pivó parece ter uma esolha mais inteligente, um algoritmo melhor, isso no scipy.linalg, e possivelmente, foi por causa disso que ocorreu resultados estranhos usando as funções feitas do 0!